package money

type currency struct {
	IsoNumeric         int
	Name               string
	Symbol             string
	SymbolFirst        bool
	AlternateSymbols   []string
	ThousandsSeparator string
	DecimalMark        string
	SubUnit            string
	SubUnitToUnit      int64
	HTMLEntity         string
}

var currencies = map[string]currency{
	"AED": currency{784, "United Arab Emirates Dirham", "د.إ", true, []string{"DH", "Dhs"}, ",", ".", "Fils", 100, ""},
	"AFN": currency{971, "Afghan Afghani", "؋", false, []string{"Af", "Afs"}, ",", ".", "Pul", 100, ""},
	"ALL": currency{8, "Albanian Lek", "L", false, []string{"Lek"}, ",", ".", "Qintar", 100, ""},
	"AMD": currency{51, "Armenian Dram", "դր.", false, []string{"dram"}, ",", ".", "Luma", 100, ""},
	"ANG": currency{532, "Netherlands Antillean Gulden", "ƒ", true, []string{"NAƒ", "NAf", "f"}, ".", ",", "Cent", 100, "&#x0192;"},
	"AOA": currency{973, "Angolan Kwanza", "Kz", false, []string{}, ",", ".", "Cêntimo", 100, ""},
	"ARS": currency{32, "Argentine Peso", "$", true, []string{"$m/n", "m$n"}, ".", ",", "Centavo", 100, "&#x20B1;"},
	"AUD": currency{36, "Australian Dollar", "$", true, []string{"A$"}, ",", ".", "Cent", 100, "$"},
	"AWG": currency{533, "Aruban Florin", "ƒ", false, []string{"Afl"}, ",", ".", "Cent", 100, "&#x0192;"},
	"AZN": currency{944, "Azerbaijani Manat", "₼", true, []string{"m", "man"}, ",", ".", "Qəpik", 100, ""},
	"BAM": currency{977, "Bosnia and Herzegovina Convertible Mark", "КМ", true, []string{"KM"}, ",", ".", "Fening", 100, ""},
	"BBD": currency{52, "Barbadian Dollar", "$", false, []string{"Bds$"}, ",", ".", "Cent", 100, "$"},
	"BDT": currency{50, "Bangladeshi Taka", "৳", true, []string{"Tk"}, ",", ".", "Paisa", 100, ""},
	"BGN": currency{975, "Bulgarian Lev", "лв", false, []string{"lev", "leva", "лев", "лева"}, ",", ".", "Stotinka", 100, ""},
	"BHD": currency{48, "Bahraini Dinar", "ب.د", true, []string{"BD"}, ",", ".", "Fils", 1000, ""},
	"BIF": currency{108, "Burundian Franc", "Fr", false, []string{"FBu"}, ",", ".", "Centime", 100, ""},
	"BMD": currency{60, "Bermudian Dollar", "$", true, []string{"BD$"}, ",", ".", "Cent", 100, "$"},
	"BND": currency{96, "Brunei Dollar", "$", true, []string{"B$"}, ",", ".", "Sen", 100, "$"},
	"BOB": currency{68, "Bolivian Boliviano", "Bs.", true, []string{"Bs"}, ",", ".", "Centavo", 100, ""},
	"BRL": currency{986, "Brazilian Real", "R$", true, []string{}, ".", ",", "Centavo", 100, "R$"},
	"BSD": currency{44, "Bahamian Dollar", "$", true, []string{"B$"}, ",", ".", "Cent", 100, "$"},
	"BTC": currency{0, "Bitcoin", "B⃦", true, []string{}, ",", ".", "Satoshi", 100000000, ""},
	"BTN": currency{64, "Bhutanese Ngultrum", "Nu.", false, []string{"Nu"}, ",", ".", "Chertrum", 100, ""},
	"BWP": currency{72, "Botswana Pula", "P", true, []string{}, ",", ".", "Thebe", 100, ""},
	"BYR": currency{974, "Belarusian Ruble", "Br", false, []string{""}, ",", ".", "Kapyeyka", 100, ""},
	"BZD": currency{84, "Belize Dollar", "$", true, []string{"BZ$"}, ",", ".", "Cent", 100, "$"},
	"CAD": currency{124, "Canadian Dollar", "$", true, []string{"C$", "CAD$"}, ",", ".", "Cent", 100, "$"},
	"CDF": currency{976, "Congolese Franc", "Fr", false, []string{"FC"}, ",", ".", "Centime", 100, ""},
	"CHF": currency{756, "Swiss Franc", "Fr", true, []string{"SFr", "CHF"}, ",", ".", "Rappen", 100, ""},
	"CLF": currency{990, "Unidad de Fomento", "UF", true, []string{}, ".", ",", "Peso", 1, "&#x20B1;"},
	"CLP": currency{152, "Chilean Peso", "$", true, []string{}, ".", ",", "Peso", 100, "&#36;"},
	"CNY": currency{156, "Chinese Renminbi Yuan", "¥", true, []string{"CN¥", "元", "CN元"}, ",", ".", "Fen", 100, "￥"},
	"COP": currency{170, "Colombian Peso", "$", true, []string{"COL$"}, ".", ",", "Centavo", 100, "&#x20B1;"},
	"CRC": currency{188, "Costa Rican Colón", "₡", true, []string{"¢"}, ".", ",", "Céntimo", 100, "&#x20A1;"},
	"CUC": currency{931, "Cuban Convertible Peso", "$", false, []string{"CUC$"}, ",", ".", "Centavo", 100, ""},
	"CUP": currency{192, "Cuban Peso", "$", true, []string{"$MN"}, ",", ".", "Centavo", 100, "&#x20B1;"},
	"CVE": currency{132, "Cape Verdean Escudo", "$", false, []string{"Esc"}, ",", ".", "Centavo", 100, ""},
	"CZK": currency{203, "Czech Koruna", "Kč", false, []string{}, ".", ",", "Haléř", 100, ""},
	"DJF": currency{262, "Djiboutian Franc", "Fdj", false, []string{}, ",", ".", "Centime", 100, ""},
	"DKK": currency{208, "Danish Krone", "kr", false, []string{",-"}, ".", ",", "Øre", 100, ""},
	"DOP": currency{214, "Dominican Peso", "$", true, []string{"RD$"}, ",", ".", "Centavo", 100, "&#x20B1;"},
	"DZD": currency{12, "Algerian Dinar", "د.ج", false, []string{"DA"}, ",", ".", "Centime", 100, ""},
	"EEK": currency{233, "Estonian Kroon", "KR", false, []string{}, ",", ".", "Sent", 100, ""},
	"EGP": currency{818, "Egyptian Pound", "ج.م", true, []string{"LE", "E£", "L.E."}, ",", ".", "Piastre", 100, "&#x00A3;"},
	"ERN": currency{232, "Eritrean Nakfa", "Nfk", false, []string{}, ",", ".", "Cent", 100, ""},
	"ETB": currency{230, "Ethiopian Birr", "Br", false, []string{}, ",", ".", "Santim", 100, ""},
	"EUR": currency{978, "Euro", "€", true, []string{}, ".", ",", "Cent", 100, "&#x20AC;"},
	"FJD": currency{242, "Fijian Dollar", "$", false, []string{"FJ$"}, ",", ".", "Cent", 100, "$"},
	"FKP": currency{238, "Falkland Pound", "£", false, []string{"FK£"}, ",", ".", "Penny", 100, "&#x00A3;"},
	"GBP": currency{826, "British Pound", "£", true, []string{}, ",", ".", "Penny", 100, "&#x00A3;"},
	"GEL": currency{981, "Georgian Lari", "ლ", false, []string{"lari"}, ",", ".", "Tetri", 100, ""},
	"GHS": currency{936, "Ghanaian Cedi", "₵", true, []string{"GH¢", "GH₵"}, ",", ".", "Pesewa", 100, "&#x20B5;"},
	"GIP": currency{292, "Gibraltar Pound", "£", true, []string{}, ",", ".", "Penny", 100, "&#x00A3;"},
	"GMD": currency{270, "Gambian Dalasi", "D", false, []string{}, ",", ".", "Butut", 100, ""},
	"GNF": currency{324, "Guinean Franc", "Fr", false, []string{"FG", "GFr"}, ",", ".", "Centime", 100, ""},
	"GTQ": currency{320, "Guatemalan Quetzal", "Q", true, []string{}, ",", ".", "Centavo", 100, ""},
	"GYD": currency{328, "Guyanese Dollar", "$", false, []string{"G$"}, ",", ".", "Cent", 100, "$"},
	"HKD": currency{344, "Hong Kong Dollar", "$", true, []string{"HK$"}, ",", ".", "Cent", 100, "$"},
	"HNL": currency{340, "Honduran Lempira", "L", true, []string{}, ",", ".", "Centavo", 100, ""},
	"HRK": currency{191, "Croatian Kuna", "kn", true, []string{}, ".", ",", "Lipa", 100, ""},
	"HTG": currency{332, "Haitian Gourde", "G", false, []string{}, ",", ".", "Centime", 100, ""},
	"HUF": currency{348, "Hungarian Forint", "Ft", false, []string{}, ".", ",", "Fillér", 100, ""},
	"IDR": currency{360, "Indonesian Rupiah", "Rp", true, []string{}, ".", ",", "Sen", 100, ""},
	"ILS": currency{376, "Israeli New Sheqel", "₪", true, []string{"ש״ח", "NIS"}, ",", ".", "Agora", 100, "&#x20AA;"},
	"INR": currency{356, "Indian Rupee", "₹", true, []string{"Rs", "৳", "૱", "௹", "रु", "₨"}, ",", ".", "Paisa", 100, "&#x20b9;"},
	"IQD": currency{368, "Iraqi Dinar", "ع.د", false, []string{}, ",", ".", "Fils", 1000, ""},
	"IRR": currency{364, "Iranian Rial", "﷼", true, []string{}, ",", ".", "Dinar", 100, "&#xFDFC;"},
	"ISK": currency{352, "Icelandic Króna", "kr", true, []string{"Íkr"}, ".", ",", "Eyrir", 100, ""},
	"JEP": currency{0, "Jersey Pound", "£", true, []string{}, ",", ".", "Penny", 100, "&#x00A3;"},
	"JMD": currency{388, "Jamaican Dollar", "$", true, []string{"J$"}, ",", ".", "Cent", 100, "$"},
	"JOD": currency{400, "Jordanian Dinar", "د.ا", true, []string{"JD"}, ",", ".", "Piastre", 100, ""},
	"JPY": currency{392, "Japanese Yen", "¥", true, []string{"円", "圓"}, ",", ".", "", 1, "&#x00A5;"},
	"KES": currency{404, "Kenyan Shilling", "KSh", true, []string{"Sh"}, ",", ".", "Cent", 100, ""},
	"KGS": currency{417, "Kyrgyzstani Som", "som", false, []string{"сом"}, ",", ".", "Tyiyn", 100, ""},
	"KHR": currency{116, "Cambodian Riel", "៛", false, []string{}, ",", ".", "Sen", 100, "&#x17DB;"},
	"KMF": currency{174, "Comorian Franc", "Fr", false, []string{"CF"}, ",", ".", "Centime", 100, ""},
	"KPW": currency{408, "North Korean Won", "₩", false, []string{}, ",", ".", "Chŏn", 100, "&#x20A9;"},
	"KRW": currency{410, "South Korean Won", "₩", true, []string{}, ",", ".", "", 100, "&#x20A9;"},
	"KWD": currency{414, "Kuwaiti Dinar", "د.ك", true, []string{"K.D."}, ",", ".", "Fils", 1000, ""},
	"KYD": currency{136, "Cayman Islands Dollar", "$", true, []string{"CI$"}, ",", ".", "Cent", 100, "$"},
	"KZT": currency{398, "Kazakhstani Tenge", "〒", false, []string{}, ",", ".", "Tiyn", 100, ""},
	"LAK": currency{418, "Lao Kip", "₭", false, []string{"₭N"}, ",", ".", "Att", 100, "&#x20AD;"},
	"LBP": currency{422, "Lebanese Pound", "ل.ل", true, []string{"£", "L£"}, ",", ".", "Piastre", 100, "&#x00A3;"},
	"LKR": currency{144, "Sri Lankan Rupee", "₨", false, []string{"රු", "ரூ", "SLRs", "/-"}, ",", ".", "Cent", 100, "&#x0BF9;"},
	"LRD": currency{430, "Liberian Dollar", "$", false, []string{"L$"}, ",", ".", "Cent", 100, "$"},
	"LSL": currency{426, "Lesotho Loti", "L", false, []string{"M"}, ",", ".", "Sente", 100, ""},
	"LTL": currency{440, "Lithuanian Litas", "Lt", false, []string{}, ",", ".", "Centas", 100, ""},
	"LVL": currency{428, "Latvian Lats", "Ls", true, []string{}, ",", ".", "Santīms", 100, ""},
	"LYD": currency{434, "Libyan Dinar", "ل.د", false, []string{"LD"}, ",", ".", "Dirham", 1000, ""},
	"MAD": currency{504, "Moroccan Dirham", "د.م.", false, []string{}, ",", ".", "Centime", 100, ""},
	"MDL": currency{498, "Moldovan Leu", "L", false, []string{"lei"}, ",", ".", "Ban", 100, ""},
	"MGA": currency{969, "Malagasy Ariary", "Ar", true, []string{}, ",", ".", "Iraimbilanja", 5, ""},
	"MKD": currency{807, "Macedonian Denar", "ден", false, []string{}, ",", ".", "Deni", 100, ""},
	"MMK": currency{104, "Myanmar Kyat", "K", false, []string{}, ",", ".", "Pya", 100, ""},
	"MNT": currency{496, "Mongolian Tögrög", "₮", false, []string{}, ",", ".", "Möngö", 100, "&#x20AE;"},
	"MOP": currency{446, "Macanese Pataca", "P", false, []string{"MOP$"}, ",", ".", "Avo", 100, ""},
	"MRO": currency{478, "Mauritanian Ouguiya", "UM", false, []string{}, ",", ".", "Khoums", 5, ""},
	"MTL": currency{470, "Maltese Lira", "₤", true, []string{"Lm"}, ",", ".", "Cent", 100, "&#x00A3;"},
	"MUR": currency{480, "Mauritian Rupee", "₨", true, []string{}, ",", ".", "Cent", 100, "&#x20A8;"},
	"MVR": currency{462, "Maldivian Rufiyaa", "MVR", false, []string{"MRF", "Rf", "/-", "ރ"}, ",", ".", "Laari", 100, ""},
	"MWK": currency{454, "Malawian Kwacha", "MK", false, []string{}, ",", ".", "Tambala", 100, ""},
	"MXN": currency{484, "Mexican Peso", "$", true, []string{"MEX$"}, ",", ".", "Centavo", 100, "$"},
	"MYR": currency{458, "Malaysian Ringgit", "RM", true, []string{}, ",", ".", "Sen", 100, ""},
	"MZN": currency{943, "Mozambican Metical", "MTn", true, []string{"MZN"}, ".", ",", "Centavo", 100, ""},
	"NAD": currency{516, "Namibian Dollar", "$", false, []string{"N$"}, ",", ".", "Cent", 100, "$"},
	"NGN": currency{566, "Nigerian Naira", "₦", true, []string{}, ",", ".", "Kobo", 100, "&#x20A6;"},
	"NIO": currency{558, "Nicaraguan Córdoba", "C$", false, []string{}, ",", ".", "Centavo", 100, ""},
	"NOK": currency{578, "Norwegian Krone", "kr", false, []string{",-"}, ".", ",", "Øre", 100, "kr"},
	"NPR": currency{524, "Nepalese Rupee", "₨", true, []string{"Rs", "रू"}, ",", ".", "Paisa", 100, "&#x20A8;"},
	"NZD": currency{554, "New Zealand Dollar", "$", true, []string{"NZ$"}, ",", ".", "Cent", 100, "$"},
	"OMR": currency{512, "Omani Rial", "ر.ع.", true, []string{}, ",", ".", "Baisa", 1000, "&#xFDFC;"},
	"PAB": currency{590, "Panamanian Balboa", "B/.", false, []string{}, ",", ".", "Centésimo", 100, ""},
	"PEN": currency{604, "Peruvian Nuevo Sol", "S/.", true, []string{}, ",", ".", "Céntimo", 100, "S/."},
	"PGK": currency{598, "Papua New Guinean Kina", "K", false, []string{}, ",", ".", "Toea", 100, ""},
	"PHP": currency{608, "Philippine Peso", "₱", true, []string{"PHP", "PhP", "P"}, ",", ".", "Centavo", 100, "&#x20B1;"},
	"PKR": currency{586, "Pakistani Rupee", "₨", true, []string{"Rs"}, ",", ".", "Paisa", 100, "&#x20A8;"},
	"PLN": currency{985, "Polish Złoty", "zł", false, []string{}, " ", ",", "Grosz", 100, "z&#322;"},
	"PYG": currency{600, "Paraguayan Guaraní", "₲", true, []string{}, ",", ".", "Céntimo", 100, "&#x20B2;"},
	"QAR": currency{634, "Qatari Riyal", "ر.ق", false, []string{"QR"}, ",", ".", "Dirham", 100, "&#xFDFC;"},
	"RON": currency{946, "Romanian Leu", "Lei", true, []string{}, ".", ",", "Bani", 100, ""},
	"RSD": currency{941, "Serbian Dinar", "РСД", true, []string{"RSD", "din", "дин"}, ",", ".", "Para", 100, ""},
	"RUB": currency{643, "Russian Ruble", "₽", false, []string{"руб.", "р."}, ".", ",", "Kopeck", 100, "&#x20BD;"},
	"RWF": currency{646, "Rwandan Franc", "FRw", false, []string{"RF", "R₣"}, ",", ".", "Centime", 100, ""},
	"SAR": currency{682, "Saudi Riyal", "ر.س", true, []string{"SR", "﷼"}, ",", ".", "Hallallah", 100, "&#xFDFC;"},
	"SBD": currency{90, "Solomon Islands Dollar", "$", false, []string{"SI$"}, ",", ".", "Cent", 100, "$"},
	"SCR": currency{690, "Seychellois Rupee", "₨", false, []string{"SRe", "SR"}, ",", ".", "Cent", 100, "&#x20A8;"},
	"SDG": currency{938, "Sudanese Pound", "£", true, []string{}, ",", ".", "Piastre", 100, ""},
	"SEK": currency{752, "Swedish Krona", "kr", false, []string{":-"}, " ", ",", "Öre", 100, ""},
	"SGD": currency{702, "Singapore Dollar", "$", true, []string{"S$"}, ",", ".", "Cent", 100, "$"},
	"SHP": currency{654, "Saint Helenian Pound", "£", false, []string{}, ",", ".", "Penny", 100, "&#x00A3;"},
	"SKK": currency{703, "Slovak Koruna", "Sk", true, []string{}, ",", ".", "Halier", 100, ""},
	"SLL": currency{694, "Sierra Leonean Leone", "Le", false, []string{}, ",", ".", "Cent", 100, ""},
	"SOS": currency{706, "Somali Shilling", "Sh", false, []string{"Sh.So"}, ",", ".", "Cent", 100, ""},
	"SRD": currency{968, "Surinamese Dollar", "$", false, []string{}, ",", ".", "Cent", 100, ""},
	"SSP": currency{728, "South Sudanese Pound", "£", false, []string{}, ",", ".", "piaster", 100, "&#x00A3;"},
	"STD": currency{678, "São Tomé and Príncipe Dobra", "Db", false, []string{}, ",", ".", "Cêntimo", 100, ""},
	"SVC": currency{222, "Salvadoran Colón", "₡", true, []string{"¢"}, ",", ".", "Centavo", 100, "&#x20A1;"},
	"SYP": currency{760, "Syrian Pound", "£S", false, []string{"£", "ل.س", "LS", "الليرة السورية"}, ",", ".", "Piastre", 100, "&#x00A3;"},
	"SZL": currency{748, "Swazi Lilangeni", "L", true, []string{"E"}, ",", ".", "Cent", 100, ""},
	"THB": currency{764, "Thai Baht", "฿", true, []string{}, ",", ".", "Satang", 100, "&#x0E3F;"},
	"TJS": currency{972, "Tajikistani Somoni", "ЅМ", false, []string{}, ",", ".", "Diram", 100, ""},
	"TMT": currency{934, "Turkmenistani Manat", "T", false, []string{}, ",", ".", "Tenge", 100, ""},
	"TND": currency{788, "Tunisian Dinar", "د.ت", false, []string{"TD", "DT"}, ",", ".", "Millime", 1000, ""},
	"TOP": currency{776, "Tongan Paʻanga", "T$", true, []string{"PT"}, ",", ".", "Seniti", 100, ""},
	"TRY": currency{949, "Turkish Lira", "₺", false, []string{"TL"}, ".", ",", "kuruş", 100, ""},
	"TTD": currency{780, "Trinidad and Tobago Dollar", "$", false, []string{"TT$"}, ",", ".", "Cent", 100, "$"},
	"TWD": currency{901, "New Taiwan Dollar", "$", true, []string{"NT$"}, ",", ".", "Cent", 100, "$"},
	"TZS": currency{834, "Tanzanian Shilling", "Sh", true, []string{}, ",", ".", "Cent", 100, ""},
	"UAH": currency{980, "Ukrainian Hryvnia", "₴", false, []string{}, ",", ".", "Kopiyka", 100, "&#x20B4;"},
	"UGX": currency{800, "Ugandan Shilling", "USh", false, []string{}, ",", ".", "Cent", 100, ""},
	"USD": currency{840, "United States Dollar", "$", true, []string{"US$"}, ",", ".", "Cent", 100, "$"},
	"UYU": currency{858, "Uruguayan Peso", "$", true, []string{"$U"}, ".", ",", "Centésimo", 100, "&#x20B1;"},
	"UZS": currency{860, "Uzbekistani Som", "", false, []string{}, ",", ".", "Tiyin", 100, ""},
	"VEF": currency{937, "Venezuelan Bolívar", "Bs F", true, []string{"Bs.F", "Bs"}, ".", ",", "Céntimo", 100, ""},
	"VND": currency{704, "Vietnamese Đồng", "₫", true, []string{}, ".", ",", "Hào", 1, "&#x20AB;"},
	"VUV": currency{548, "Vanuatu Vatu", "Vt", true, []string{}, ",", ".", "", 1, ""},
	"WST": currency{882, "Samoan Tala", "T", false, []string{"WS$", "SAT", "ST"}, ",", ".", "Sene", 100, ""},
	"XAF": currency{950, "Central African Cfa Franc", "Fr", false, []string{"FCFA"}, ",", ".", "Centime", 100, ""},
	"XAG": currency{961, "Silver (Troy Ounce)", "oz t", false, []string{}, ",", ".", "oz", 1, ""},
	"XAU": currency{959, "Gold (Troy Ounce)", "oz t", false, []string{}, ",", ".", "oz", 1, ""},
	"XCD": currency{951, "East Caribbean Dollar", "$", true, []string{"EC$"}, ",", ".", "Cent", 100, "$"},
	"XDR": currency{960, "Special Drawing Rights", "SDR", false, []string{"XDR"}, ",", ".", "", 1, "$"},
	"XOF": currency{952, "West African Cfa Franc", "Fr", false, []string{"CFA"}, ",", ".", "Centime", 100, ""},
	"XPF": currency{953, "Cfp Franc", "Fr", false, []string{"F"}, ",", ".", "Centime", 100, ""},
	"YER": currency{886, "Yemeni Rial", "﷼", false, []string{}, ",", ".", "Fils", 100, "&#xFDFC;"},
	"ZAR": currency{710, "South African Rand", "R", true, []string{}, ",", ".", "Cent", 100, "&#x0052;"},
	"ZMK": currency{894, "Zambian Kwacha", "ZK", false, []string{}, ",", ".", "Ngwee", 100, ""},
	"ZMW": currency{967, "Zambian Kwacha", "ZK", false, []string{}, ",", ".", "Ngwee", 100, ""},
	"ZWD": currency{716, "Zimbabwean Dollar", "$", true, []string{"Z$"}, ",", ".", "Cent", 100, "$"},
	"ZWL": currency{932, "Zimbabwean Dollar", "$", true, []string{"Z$"}, ",", ".", "Cent", 100, "$"},
	"ZWN": currency{942, "Zimbabwean Dollar", "$", true, []string{"Z$"}, ",", ".", "Cent", 100, "$"},
	"ZWR": currency{935, "Zimbabwean Dollar", "$", true, []string{"Z$"}, ",", ".", "Cent", 100, "$"},
}
